export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const CREATE_STREAM = "CREATE_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const GET_STREAM_TOKEN = "GET_STREAM_TOKEN";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const INIT_PAYMENT = "INIT_PAYMENT";
export const DEACTIVATE_PAYMENT = "DEACTIVATE_PAYMENT";
export const SUBMIT_PAYMENT = "SUBMIT_PAYMENT";
export const PROCESS_PAYMENT = "PROCESS_PAYMENT";
export const SET_AMOUNT = "SET_AMOUNT";

export const CREATE_MEDIA = "CREATE_MEDIA";
export const SET_STREAM = "SET_STREAM";
export const RESET_STREAM = "RESET_STREAM";
export const TOGGLE_MUTE_AUDIO = "TOGGLE_MUTE_AUDIO";
export const TOGGLE_MUTE_VIDEO = "TOGGLE_MUTE_VIDEO";

export const CREATE_COLLECTED = "CREATE_COLLECTED";
export const FETCH_COLLECTED = "FETCH_COLLECTED";
